# Generated by Django 6.0 on 2026-02-07 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='aprobado',
            field=models.BooleanField(default=False),
        ),
    ]
