# Generated by Django 6.0 on 2026-02-14 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_ordencompra_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordencompra',
            name='numero_compra',
        ),
    ]
